// This file was auto-generated by Fern from our API Definition.

/**
 * Add contract abi response object
 */
export interface AddContractAbiResponse {
    result?: AddContractAbiResponse.Result;
}

export namespace AddContractAbiResponse {
    export interface Result {
        contractAddress?: string;
        network?: Result.Network;
        name?: string;
        abi?: Record<string, unknown>[];
        status?: string;
        source?: string;
        message?: string;
        tenantId?: string;
        userId?: string;
    }

    export namespace Result {
        export const Network = {
            TBtc: "tBTC",
            TEth: "tETH",
            Avax: "AVAX",
            Fuji: "FUJI",
            Sandbox: "SANDBOX",
        } as const;
        export type Network = (typeof Network)[keyof typeof Network];
    }
}
