// This file was auto-generated by Fern from our API Definition.

export interface AddContractAbiResultDto {
    contractAddress?: string;
    network?: string;
    name?: string;
    abi?: Record<string, unknown>;
    status?: string;
    source?: string;
    message?: string;
    tenantId?: string;
    userId?: string;
}
