// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Addresses response object
 */
export interface AddressesResponse {
    data?: OumlaSdkApi.AddressData[];
    pagination?: OumlaSdkApi.Pagination;
}
