// This file was auto-generated by Fern from our API Definition.

/**
 * Address data object
 */
export interface AddressData {
    address?: string;
    date?: string;
    label?: string;
    sub?: string;
    network?: AddressData.Network;
    /** Balance as decimal string */
    balance?: string;
    reference?: string;
    path?: string;
    id?: string;
    miniWalletId?: string;
}

export namespace AddressData {
    export const Network = {
        TBtc: "tBTC",
        TEth: "tETH",
        Avax: "AVAX",
        Fuji: "FUJI",
        Sandbox: "SANDBOX",
    } as const;
    export type Network = (typeof Network)[keyof typeof Network];
}
