// This file was auto-generated by Fern from our API Definition.

/** Address family (EVM, BITCOIN, MOVE, etc.) */
export const AddressFamily = {
    Evm: "EVM",
    Bitcoin: "BITCOIN",
    Move: "MOVE",
    Solana: "SOLANA",
    Cosmos: "COSMOS",
    Tron: "TRON",
    Starknet: "STARKNET",
} as const;
export type AddressFamily = (typeof AddressFamily)[keyof typeof AddressFamily];
