// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Assets response object
 */
export interface AssetsResponse {
    assets?: OumlaSdkApi.AssetData[];
    pagination?: OumlaSdkApi.Pagination;
}
