// This file was auto-generated by Fern from our API Definition.

export interface BadRequestErrorBody {
    /** One of: ERR-010: The request could not be processed. */
    code?: "ERR_010";
    /** Client-facing message for this error code (see table above). */
    message?: string;
    /** Error category for grouping and handling. */
    category: BadRequestErrorBody.Category;
    /** HTTP status code */
    statusCode: number;
    /** Request path that produced the error */
    path: string;
    /** ISO 8601 timestamp */
    timestamp: string;
    /** Request ID for tracing */
    requestId?: string;
}

export namespace BadRequestErrorBody {
    /** Error category for grouping and handling. */
    export const Category = {
        Conflict: "CONFLICT",
        Validation: "VALIDATION",
        Cryptographic: "CRYPTOGRAPHIC",
        Network: "NETWORK",
        Database: "DATABASE",
        ExternalService: "EXTERNAL_SERVICE",
        UnknownError: "UNKNOWN_ERROR",
        Resource: "RESOURCE",
        Authorization: "AUTHORIZATION",
        System: "SYSTEM",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
}
