// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Collections response object
 */
export interface CollectionsResponse {
    collections?: OumlaSdkApi.CollectionData[];
    total?: number;
    message?: string;
}
