// This file was auto-generated by Fern from our API Definition.

/**
 * Collection data object
 */
export interface CollectionData {
    id?: string;
    status?: string;
    type?: string;
    displayName?: string;
    createdAt?: string;
    updatedAt?: string;
    network?: CollectionData.Network;
    collectionMetadata?: CollectionData.CollectionMetadata;
}

export namespace CollectionData {
    export const Network = {
        TBtc: "tBTC",
        TEth: "tETH",
        Avax: "AVAX",
        Fuji: "FUJI",
        Sandbox: "SANDBOX",
    } as const;
    export type Network = (typeof Network)[keyof typeof Network];

    export interface CollectionMetadata {
        name?: string;
        symbol?: string;
        standard?: string;
        contractAddress?: string;
    }
}
