// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Collection response object
 */
export interface CollectionResponse {
    collection?: OumlaSdkApi.CollectionData;
}
