// This file was auto-generated by Fern from our API Definition.

/**
 * Collection token details response object
 */
export interface CollectionTokenDetailsResponse {
    collcetion?: CollectionTokenDetailsResponse.Collcetion;
}

export namespace CollectionTokenDetailsResponse {
    export interface Collcetion {
        id?: string;
        collectionId?: string;
        name?: string;
        symbol?: string;
        network?: Collcetion.Network;
        addressId?: string;
        contractAddress?: string;
        status?: Collcetion.Status;
        recipientAddress?: string;
        mintTransactionHash?: string;
        burnTransactionHash?: string;
        mintedAt?: string;
        burnedAt?: string;
        metadata?: Collcetion.Metadata;
        mintRecord?: Collcetion.MintRecord;
        burnRecord?: Collcetion.BurnRecord;
    }

    export namespace Collcetion {
        export const Network = {
            TBtc: "tBTC",
            TEth: "tETH",
            Avax: "AVAX",
            Fuji: "FUJI",
            Sandbox: "SANDBOX",
        } as const;
        export type Network = (typeof Network)[keyof typeof Network];
        export const Status = {
            Active: "ACTIVE",
            Burned: "BURNED",
        } as const;
        export type Status = (typeof Status)[keyof typeof Status];

        export interface Metadata {
            name?: string;
            description?: string;
            image?: string;
            animation_url?: string;
            external_url?: string;
            attributes?: Metadata.Attributes.Item[];
        }

        export namespace Metadata {
            export type Attributes = Attributes.Item[];

            export namespace Attributes {
                export interface Item {
                    trait_type?: string;
                    value?: string;
                    display_type?: string;
                }
            }
        }

        export interface MintRecord {
            id?: string;
            amount?: string;
            note?: string;
            status?: string;
            createdAt?: string;
            updatedAt?: string;
        }

        export interface BurnRecord {
            id?: string;
            amount?: string;
            note?: string;
            status?: string;
            createdAt?: string;
            updatedAt?: string;
        }
    }
}
