// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

export interface CollectionTokenDetailMetadataDto {
    name?: string;
    description?: string;
    image?: string;
    animation_url?: string;
    external_url?: string;
    attributes?: OumlaSdkApi.MetadataAttributeDto[];
}
