// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

export interface CollectionTokenDetailDto {
    id?: string;
    collectionId?: string;
    name?: string;
    symbol?: string;
    network?: string;
    addressId?: string;
    contractAddress?: string;
    status?: string;
    recipientAddress?: string;
    mintTransactionHash?: string;
    burnTransactionHash?: string;
    mintedAt?: string;
    burnedAt?: string;
    metadata?: OumlaSdkApi.CollectionTokenDetailMetadataDto;
    mintRecord?: OumlaSdkApi.MintOrBurnRecordSummaryDto;
    burnRecord?: OumlaSdkApi.MintOrBurnRecordSummaryDto;
}
