// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

export interface ConstructorParameterDto {
    name: string;
    description?: string;
    internalType?: string;
    type: string;
    components?: OumlaSdkApi.ComponentDto[];
    value?: Record<string, unknown>;
}
