// This file was auto-generated by Fern from our API Definition.

export const ContractTemplateFunctionType = {
    Function: "function",
    Constructor: "constructor",
    Event: "event",
    Error: "error",
    Fallback: "fallback",
    Receive: "receive",
} as const;
export type ContractTemplateFunctionType =
    (typeof ContractTemplateFunctionType)[keyof typeof ContractTemplateFunctionType];
