// This file was auto-generated by Fern from our API Definition.

/**
 * Contract template response object
 */
export interface ContractTemplateResponse {
    contract?: ContractTemplateResponse.Contract;
}

export namespace ContractTemplateResponse {
    export interface Contract {
        id?: string;
        name?: string;
        description?: string;
        longDescription?: string;
        bytecode?: string;
        sourceCode?: string;
        type?: string;
        docs?: Record<string, unknown>;
    }
}
