// This file was auto-generated by Fern from our API Definition.

/**
 * Contract abi response object
 */
export interface ContractAbiResponse {
    contractAbi?: ContractAbiResponse.ContractAbi;
}

export namespace ContractAbiResponse {
    export interface ContractAbi {
        abi?: Record<string, unknown>[];
        contractAddress?: string;
        network?: ContractAbi.Network;
        implementationAddress?: string;
        status?: string;
        source?: string;
    }

    export namespace ContractAbi {
        export const Network = {
            TBtc: "tBTC",
            TEth: "tETH",
            Avax: "AVAX",
            Fuji: "FUJI",
            Sandbox: "SANDBOX",
        } as const;
        export type Network = (typeof Network)[keyof typeof Network];
    }
}
