// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Contract templates response object
 */
export interface ContractTemplatesResponse {
    result?: ContractTemplatesResponse.Result;
}

export namespace ContractTemplatesResponse {
    export interface Result {
        data?: OumlaSdkApi.ContractTemplateData[];
        next?: number;
        count?: number;
    }
}
