// This file was auto-generated by Fern from our API Definition.

/**
 * Contract functions response object
 */
export interface ContractFunctionsResponse {
    contractFunction?: ContractFunctionsResponse.ContractFunction.Item[];
}

export namespace ContractFunctionsResponse {
    export type ContractFunction = ContractFunction.Item[];

    export namespace ContractFunction {
        export interface Item {
            id?: string;
            name?: string;
            stateMutability?: Item.StateMutability;
            type?: Item.Type;
            inputs?: Record<string, unknown>[];
            outputs?: Record<string, unknown>[];
        }

        export namespace Item {
            export const StateMutability = {
                Pure: "pure",
                View: "view",
                Nonpayable: "nonpayable",
                Payable: "payable",
            } as const;
            export type StateMutability = (typeof StateMutability)[keyof typeof StateMutability];
            export const Type = {
                Function: "function",
                Constructor: "constructor",
                Event: "event",
                Error: "error",
                Fallback: "fallback",
                Receive: "receive",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
        }
    }
}
