// This file was auto-generated by Fern from our API Definition.

export const ContractTemplateFunctionVisibilityType = {
    Pure: "pure",
    View: "view",
    Nonpayable: "nonpayable",
    Payable: "payable",
} as const;
export type ContractTemplateFunctionVisibilityType =
    (typeof ContractTemplateFunctionVisibilityType)[keyof typeof ContractTemplateFunctionVisibilityType];
