// This file was auto-generated by Fern from our API Definition.

export interface ContractAbiResultDto {
    /** Contract ABI (array of function/event entries) */
    abi?: string[];
    contractAddress?: string;
    implementationAddress?: string;
    network?: string;
    status?: string;
    source?: string;
}
