// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Contract template data object
 */
export interface ContractTemplateData {
    id?: string;
    organizationId?: string;
    name?: string;
    description?: string;
    longDescription?: string;
    bytecode?: string;
    sourceCode?: string;
    type?: string;
    docs?: Record<string, unknown>;
    attributes?: Record<string, unknown>;
    abi?: OumlaSdkApi.ContractTemplateFunction[];
    createdAt?: string;
    updatedAt?: string;
}
