// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

export interface ContractFunDto {
    name?: string;
    stateMutability?: OumlaSdkApi.ContractTemplateFunctionVisibilityType;
    type: OumlaSdkApi.ContractTemplateFunctionType;
    inputs: OumlaSdkApi.InputOutputDto[];
    outputs?: OumlaSdkApi.InputOutputDto[];
    description?: string;
    anonymous?: boolean;
}
