// This file was auto-generated by Fern from our API Definition.

export interface CreateAddressRequest {
    /** Profile reference */
    reference: string;
    /** Blockchain network */
    network: CreateAddressRequest.Network;
    /** Client share for signing */
    clientShare: string;
}

export namespace CreateAddressRequest {
    /** Blockchain network */
    export const Network = {
        Btc: "BTC",
        TBtc: "tBTC",
        Eth: "ETH",
        TEth: "tETH",
    } as const;
    export type Network = (typeof Network)[keyof typeof Network];
}
