// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

export interface CreateCollectionWorkflowResponseDto {
    workflowResult: OumlaSdkApi.WorkflowStartResultDto;
}
