// This file was auto-generated by Fern from our API Definition.

/**
 * Create address response object
 */
export interface CreateAddressResponse {
    /** Generated address */
    data?: string;
    message?: string;
}
