// This file was auto-generated by Fern from our API Definition.

export interface CreateOrganizationRequestBodyDto {
    name: string;
    companySize: number;
    role: string;
    terms: boolean;
    country: string;
}
