// This file was auto-generated by Fern from our API Definition.

export interface CreateWalletDataDto {
    /** Profile reference that owns this wallet */
    reference: string;
    /** Network UUID */
    networkId: string;
    /** Profile type (User | Department | Merchant) */
    type: string;
    /** Wallet creation timestamp */
    date?: string;
}
