// This file was auto-generated by Fern from our API Definition.

export interface CreateContractResultDto {
    id?: string;
    name?: string;
    description?: string;
    longDescription?: string;
    bytecode?: string;
    sourceCode?: string;
    type?: string;
    docs?: Record<string, unknown>;
}
