// This file was auto-generated by Fern from our API Definition.

/**
 * Create address request object
 */
export interface CreateAddressRequest {
    /** Profile reference */
    reference: string;
    /** Blockchain network */
    network: CreateAddressRequest.Network;
    /** Client share for wallet derivation */
    clientShare: string;
}

export namespace CreateAddressRequest {
    /** Blockchain network */
    export const Network = {
        TBtc: "tBTC",
        TEth: "tETH",
        Avax: "AVAX",
        Fuji: "FUJI",
        Sandbox: "SANDBOX",
    } as const;
    export type Network = (typeof Network)[keyof typeof Network];
}
