// This file was auto-generated by Fern from our API Definition.

/**
 * Deployed contract by address response object
 */
export interface DeployedContractByAddressResponse {
    deployedContract?: DeployedContractByAddressResponse.DeployedContract;
}

export namespace DeployedContractByAddressResponse {
    export interface DeployedContract {
        id?: string;
        contractAddress?: string;
        network?: DeployedContract.Network;
        contractTemplateId?: string;
        vauldAccountId?: string;
    }

    export namespace DeployedContract {
        export const Network = {
            TBtc: "tBTC",
            TEth: "tETH",
            Avax: "AVAX",
            Fuji: "FUJI",
            Sandbox: "SANDBOX",
        } as const;
        export type Network = (typeof Network)[keyof typeof Network];
    }
}
