// This file was auto-generated by Fern from our API Definition.

/**
 * Deployed contract data object
 */
export interface DeployedContractData {
    id?: string;
    contractAddress?: string;
    network?: DeployedContractData.Network;
    contractTemplateId?: string;
}

export namespace DeployedContractData {
    export const Network = {
        TBtc: "tBTC",
        TEth: "tETH",
        Avax: "AVAX",
        Fuji: "FUJI",
        Sandbox: "SANDBOX",
    } as const;
    export type Network = (typeof Network)[keyof typeof Network];
}
