// This file was auto-generated by Fern from our API Definition.

export interface DeployedContractItemDto {
    id?: string;
    contractAddress?: string;
    network?: string;
    contractTemplateId?: string;
}
