// This file was auto-generated by Fern from our API Definition.

export interface DeployedContractByIdDto {
    id?: string;
    contractAddress?: string;
    network?: string;
    contractTemplateId?: string;
    deployerAddressId?: string;
}
