// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

export interface DocsDto {
    details?: string;
    events?: string;
    kind: DocsDto.Kind;
    methods: OumlaSdkApi.MethodDto[];
    version: string;
}

export namespace DocsDto {
    export const Kind = {
        Dev: "dev",
        User: "user",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
}
