// This file was auto-generated by Fern from our API Definition.

export interface EnabledNetworkItemDto {
    /** Network UUID */
    networkId: string;
    /** Human-readable network name */
    name: string;
    /** Network alias used by event producers */
    alias: string;
}
