// This file was auto-generated by Fern from our API Definition.

/**
 * Error response object
 */
export interface ErrorResponse {
    /** Human-readable error message */
    message: string;
    /** Error code for programmatic error handling */
    code: string;
    category: ErrorResponse.Category;
    /** HTTP status code */
    statusCode: number;
    /** API path where error occurred */
    path: string;
    /** Timestamp when error occurred (ISO 8601) */
    timestamp: string;
    /** Unique request identifier for tracking and debugging */
    requestId?: string;
    /** Array of field-specific validation errors (only present for validation errors) */
    errors?: ErrorResponse.Errors.Item[];
}

export namespace ErrorResponse {
    export const Category = {
        Conflict: "CONFLICT",
        Validation: "VALIDATION",
        Cryptographic: "CRYPTOGRAPHIC",
        Network: "NETWORK",
        Database: "DATABASE",
        ExternalService: "EXTERNAL_SERVICE",
        UnknownError: "UNKNOWN_ERROR",
        Resource: "RESOURCE",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
    export type Errors = Errors.Item[];

    export namespace Errors {
        export interface Item {
            /** Field name that caused the error */
            field: string;
            /** Error message for the field */
            message: string;
        }
    }
}
