// This file was auto-generated by Fern from our API Definition.

/**
 * Fetch contract abi response object
 */
export interface FetchContractAbiResponse {
    contractAbi?: FetchContractAbiResponse.ContractAbi;
}

export namespace FetchContractAbiResponse {
    export interface ContractAbi {
        abi?: Record<string, unknown>[];
        contractAddress?: string;
        network?: ContractAbi.Network;
        status?: string;
        source?: ContractAbi.Source;
        tenantId?: string;
        userId?: string;
    }

    export namespace ContractAbi {
        export const Network = {
            TBtc: "tBTC",
            TEth: "tETH",
            Avax: "AVAX",
            Fuji: "FUJI",
            Sandbox: "SANDBOX",
        } as const;
        export type Network = (typeof Network)[keyof typeof Network];
        export const Source = {
            TenantDatabase: "tenant_database",
            Database: "database",
            Blockchain: "blockchain",
        } as const;
        export type Source = (typeof Source)[keyof typeof Source];
    }
}
