// This file was auto-generated by Fern from our API Definition.

export interface FetchContractAbiResultDto {
    /** Contract ABI array */
    abi?: Record<string, unknown>;
    contractAddress?: string;
    network?: string;
    status?: string;
    source?: string;
    tenantId?: string;
    userId?: string;
}
