// This file was auto-generated by Fern from our API Definition.

export interface ForbiddenErrorBody {
    /** One of: ERR-009: You don't have permission to do that.; ERR-410: Error occurred */
    code?: ForbiddenErrorBody.Code;
    /** Client-facing message for this error code (see table above). */
    message?: string;
    /** Error category for grouping and handling. */
    category: ForbiddenErrorBody.Category;
    /** HTTP status code */
    statusCode: number;
    /** Request path that produced the error */
    path: string;
    /** ISO 8601 timestamp */
    timestamp: string;
    /** Request ID for tracing */
    requestId?: string;
}

export namespace ForbiddenErrorBody {
    /** One of: ERR-009: You don't have permission to do that.; ERR-410: Error occurred */
    export const Code = {
        Err009: "ERR_009",
        Err410: "ERR_410",
    } as const;
    export type Code = (typeof Code)[keyof typeof Code];
    /** Error category for grouping and handling. */
    export const Category = {
        Conflict: "CONFLICT",
        Validation: "VALIDATION",
        Cryptographic: "CRYPTOGRAPHIC",
        Network: "NETWORK",
        Database: "DATABASE",
        ExternalService: "EXTERNAL_SERVICE",
        UnknownError: "UNKNOWN_ERROR",
        Resource: "RESOURCE",
        Authorization: "AUTHORIZATION",
        System: "SYSTEM",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
}
