// This file was auto-generated by Fern from our API Definition.

export interface GetWorkflowStatusResponseDto {
    workflowId?: string;
    runId?: string;
    status?: string;
    startTime?: string;
    closeTime?: string;
    executionTime?: string;
    historyLength?: number;
    /** Workflow result payload */
    result?: Record<string, unknown>;
    error?: string;
}
