// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

export interface GetWalletsListResponseBodyDto {
    data?: OumlaSdkApi.WalletDataDto[];
    pagination?: OumlaSdkApi.PaginationMetaDto;
}
