// This file was auto-generated by Fern from our API Definition.

export interface InternalServerErrorBody {
    /** One of: ERR-019: Something went wrong on our side.; ERR-999: An unexpected error occurred. Please try again. */
    code?: InternalServerErrorBody.Code;
    /** Client-facing message for this error code (see table above). */
    message?: string;
    /** Error category for grouping and handling. */
    category: InternalServerErrorBody.Category;
    /** HTTP status code */
    statusCode: number;
    /** Request path that produced the error */
    path: string;
    /** ISO 8601 timestamp */
    timestamp: string;
    /** Request ID for tracing */
    requestId?: string;
}

export namespace InternalServerErrorBody {
    /** One of: ERR-019: Something went wrong on our side.; ERR-999: An unexpected error occurred. Please try again. */
    export const Code = {
        Err019: "ERR_019",
        Err999: "ERR_999",
    } as const;
    export type Code = (typeof Code)[keyof typeof Code];
    /** Error category for grouping and handling. */
    export const Category = {
        Conflict: "CONFLICT",
        Validation: "VALIDATION",
        Cryptographic: "CRYPTOGRAPHIC",
        Network: "NETWORK",
        Database: "DATABASE",
        ExternalService: "EXTERNAL_SERVICE",
        UnknownError: "UNKNOWN_ERROR",
        Resource: "RESOURCE",
        Authorization: "AUTHORIZATION",
        System: "SYSTEM",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
}
