// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Issue new token response object
 */
export type IssueNewTokenResponse = OumlaSdkApi.TokenData;
