// This file was auto-generated by Fern from our API Definition.

export interface MethodDto {
    name: string;
    description?: string;
    params?: Record<string, unknown>;
    returns?: Record<string, unknown>;
}
