// This file was auto-generated by Fern from our API Definition.

export interface NativeBalanceItemDto {
    id?: string;
    address?: string;
    walletId?: string;
    network?: string;
    balance?: string;
    createdAt?: string;
    updatedAt?: string;
}
