// This file was auto-generated by Fern from our API Definition.

/**
 * Native balance data object
 */
export interface NativeBalanceData {
    id?: string;
    walletId?: string;
    addressId?: string;
    network?: NativeBalanceData.Network;
    symbol?: string;
    /** Balance amount as decimal string */
    amount?: string;
    decimals?: number;
    createdAt?: string;
    updatedAt?: string;
}

export namespace NativeBalanceData {
    export const Network = {
        TBtc: "tBTC",
        TEth: "tETH",
        Avax: "AVAX",
        Fuji: "FUJI",
        Sandbox: "SANDBOX",
    } as const;
    export type Network = (typeof Network)[keyof typeof Network];
}
