// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Native balance response object
 */
export interface NativeBalanceResponse {
    balance?: OumlaSdkApi.NativeBalanceData[];
    pagination?: OumlaSdkApi.Pagination;
}
