// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

export interface NetworkItemDto {
    id: string;
    name?: string;
    alias?: string;
    chainId?: number;
    decimals: number;
    isMainnet: boolean;
    enabled: boolean;
    globalAccess: boolean;
    addressFamily: OumlaSdkApi.AddressFamily;
    slip44CoinType?: number;
    explorerUrl?: string;
    explorerWsUrl?: string;
    createdAt?: string;
    updatedAt?: string;
}
