// This file was auto-generated by Fern from our API Definition.

export interface OrganizationDto {
    /** Organization ID */
    id?: string;
    /** Organization name */
    name?: string;
    /** Organization email */
    email?: string;
    createdAt?: string;
    updatedAt?: string;
    isVerified?: boolean;
    role?: string;
    companySize?: number;
    isSubscribed?: boolean;
    sub?: string;
    country?: string;
    terms?: boolean;
}
