// This file was auto-generated by Fern from our API Definition.

export interface OrgNetworkItemDto {
    id: string;
    enabled: boolean;
    name: string;
    globalAccess: boolean;
    chainId?: number;
    isMainnet: boolean;
    addressFamily: OrgNetworkItemDto.AddressFamily;
    decimals: number;
    createdAt?: string;
    updatedAt?: string;
}

export namespace OrgNetworkItemDto {
    export const AddressFamily = {
        Evm: "EVM",
        Bitcoin: "BITCOIN",
        Move: "MOVE",
        Solana: "SOLANA",
        Cosmos: "COSMOS",
        Tron: "TRON",
        Starknet: "STARKNET",
    } as const;
    export type AddressFamily = (typeof AddressFamily)[keyof typeof AddressFamily];
}
