// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

export interface PaginatedResponse extends OumlaSdkApi.SuccessResponse {
    pagination?: PaginatedResponse.Pagination;
}

export namespace PaginatedResponse {
    export interface Pagination {
        /** Number of records skipped */
        skip: number;
        /** Number of records taken */
        take: number;
        /** Total number of elements */
        totalElements: number;
        /** Total number of pages */
        totalPages: number;
    }
}
