// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Profiles response object
 */
export interface ProfilesResponse {
    data?: ProfilesResponse.Data.Item[];
    pagination?: OumlaSdkApi.Pagination;
}

export namespace ProfilesResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            reference?: string;
            type?: string;
        }
    }
}
