// This file was auto-generated by Fern from our API Definition.

/**
 * Profile response object
 */
export interface ProfileResponse {
    data?: ProfileResponse.Data;
}

export namespace ProfileResponse {
    export interface Data {
        reference?: string;
        type?: string;
    }
}
