// This file was auto-generated by Fern from our API Definition.

/**
 * Read call function response object
 */
export interface ReadCallFunctionResponse {
    result?: ReadCallFunctionResponse.Result;
}

export namespace ReadCallFunctionResponse {
    export interface Result {
        data?: Result.Data;
        success?: boolean;
        status?: number;
    }

    export namespace Result {
        export interface Data {
            /** Decoded function result */
            result?: Record<string, unknown>;
            functionName?: string;
            contractAddress?: string;
            network?: Data.Network;
            encodedData?: string;
        }

        export namespace Data {
            export const Network = {
                TBtc: "tBTC",
                TEth: "tETH",
                Avax: "AVAX",
                Fuji: "FUJI",
                Sandbox: "SANDBOX",
            } as const;
            export type Network = (typeof Network)[keyof typeof Network];
        }
    }
}
