// This file was auto-generated by Fern from our API Definition.

export interface ReadCallDataDto {
    /** Decoded result of the read call */
    result?: Record<string, unknown>;
    functionName?: string;
    contractAddress?: string;
    network?: string;
    encodedData?: string;
}
