// This file was auto-generated by Fern from our API Definition.

export interface SuccessResponse {
    /** Response message */
    message: string;
    /** Response data */
    data?: Record<string, unknown>;
    /** Indicates successful response */
    success: boolean;
    /** HTTP status code */
    status: number;
}
