// This file was auto-generated by Fern from our API Definition.

export interface TemporalWorkflowStatusData {
    /** Temporal workflow ID */
    workflowId: string;
    /** Temporal run ID */
    runId?: string;
    /** Workflow execution status */
    status: string;
    /** Workflow start time (ISO 8601) */
    startTime: string;
    /** Workflow close time (ISO 8601) or null if running */
    closeTime?: string;
    /** Execution time (implementation-defined units) */
    executionTime?: number;
    /** Number of events in workflow history */
    historyLength: number;
    /** Workflow result payload if completed */
    result?: Record<string, unknown>;
    /** Error information if the workflow failed */
    error?: Record<string, unknown>;
}
