// This file was auto-generated by Fern from our API Definition.

/**
 * Token data object
 */
export interface TokenData {
    id?: string;
    status?: string;
    type?: string;
    displayName?: string;
    tokenMetadata?: TokenData.TokenMetadata;
}

export namespace TokenData {
    export interface TokenMetadata {
        name?: string;
        symbol?: string;
        decimals?: number;
        standard?: string;
        network?: TokenMetadata.Network;
        contractAddress?: string;
        contractTemplateId?: string;
        contractDeploymentId?: string;
        addressId?: string;
    }

    export namespace TokenMetadata {
        export const Network = {
            TBtc: "tBTC",
            TEth: "tETH",
            Avax: "AVAX",
            Fuji: "FUJI",
            Sandbox: "SANDBOX",
        } as const;
        export type Network = (typeof Network)[keyof typeof Network];
    }
}
