// This file was auto-generated by Fern from our API Definition.

export interface TokenMetadataDto {
    name?: string;
    symbol?: string;
    decimals?: number;
    standard?: string;
    network?: string;
    contractAddress?: string;
    contractTemplateId?: string;
    contractDeploymentId?: string;
    addressId?: string;
}
