// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Transactions by profile response object
 */
export interface TransactionsByProfileResponse {
    transactions?: OumlaSdkApi.TransactionData[];
    pagination?: OumlaSdkApi.Pagination;
}
