// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Transactions response object
 */
export interface TransactionsResponse {
    data?: OumlaSdkApi.TransactionData[];
    pagination?: OumlaSdkApi.Pagination;
}
