// This file was auto-generated by Fern from our API Definition.

export interface TransactionReceiptLogDto {
    address?: string;
    topics?: string[];
    data?: string;
    blockNumber?: string;
    transactionHash?: string;
    transactionIndex?: number;
    blockHash?: string;
    logIndex?: number;
    removed?: boolean;
}
