// This file was auto-generated by Fern from our API Definition.

export interface TransactionItemDto {
    addressFrom?: string;
    addressTo?: string;
    amount?: string;
    date?: string;
    isMempool?: boolean;
    isSpent?: boolean;
    status?: string;
    updatedAt?: string;
    createdAt?: string;
    type?: string;
    networkId?: string;
    txid?: string;
    contractAddress?: string;
    tokenId?: string;
    txType?: string;
    fee?: string;
}
