// This file was auto-generated by Fern from our API Definition.

/**
 * Transaction data object
 */
export interface TransactionData {
    addressFrom?: string;
    addressTo?: string;
    /** Transaction amount as decimal string */
    amount?: string;
    date?: string;
    isMempool?: boolean;
    isSpent?: boolean;
    status?: TransactionData.Status;
    updatedAt?: string;
    createdAt?: string;
    type?: TransactionData.Type;
    network?: TransactionData.Network;
    txid?: string;
    contractAddress?: string;
    tokenId?: string;
    txType?: string;
    /** Transaction fee as decimal string */
    fee?: string;
}

export namespace TransactionData {
    export const Status = {
        Pending: "Pending",
        Confirmed: "Confirmed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const Type = {
        Withdraw: "Withdraw",
        Deposit: "Deposit",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const Network = {
        TBtc: "tBTC",
        TEth: "tETH",
        Avax: "AVAX",
        Fuji: "FUJI",
        Sandbox: "SANDBOX",
    } as const;
    export type Network = (typeof Network)[keyof typeof Network];
}
