// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

export interface TransactionReceiptDto {
    blockHash?: string;
    blockNumber?: string;
    contractAddress?: string;
    cumulativeGasUsed?: string;
    effectiveGasPrice?: string;
    from?: string;
    gasUsed?: string;
    logs?: OumlaSdkApi.TransactionReceiptLogDto[];
    logsBloom?: string;
    status?: number;
    to?: string;
    transactionHash?: string;
    transactionIndex?: number;
    type?: number;
}
