// This file was auto-generated by Fern from our API Definition.

/**
 * Transaction receipt response object
 */
export interface TransactionReceiptResponse {
    /** Transaction receipt object from blockchain */
    receipt?: TransactionReceiptResponse.Receipt;
}

export namespace TransactionReceiptResponse {
    /**
     * Transaction receipt object from blockchain
     */
    export interface Receipt {
        transactionHash?: string;
        blockNumber?: number;
        blockHash?: string;
        transactionIndex?: number;
        from?: string;
        to?: string;
        gasUsed?: string;
        effectiveGasPrice?: string;
        status?: number;
        logs?: Record<string, unknown>[];
    }
}
