// This file was auto-generated by Fern from our API Definition.

export interface UnauthorizedErrorBody {
    /** One of: ERR-008: You need to sign in to continue.; ERR-011: Your session is invalid or expired. Please sign in again. */
    code?: UnauthorizedErrorBody.Code;
    /** Client-facing message for this error code (see table above). */
    message?: string;
    /** Error category for grouping and handling. */
    category: UnauthorizedErrorBody.Category;
    /** HTTP status code */
    statusCode: number;
    /** Request path that produced the error */
    path: string;
    /** ISO 8601 timestamp */
    timestamp: string;
    /** Request ID for tracing */
    requestId?: string;
}

export namespace UnauthorizedErrorBody {
    /** One of: ERR-008: You need to sign in to continue.; ERR-011: Your session is invalid or expired. Please sign in again. */
    export const Code = {
        Err008: "ERR_008",
        Err011: "ERR_011",
    } as const;
    export type Code = (typeof Code)[keyof typeof Code];
    /** Error category for grouping and handling. */
    export const Category = {
        Conflict: "CONFLICT",
        Validation: "VALIDATION",
        Cryptographic: "CRYPTOGRAPHIC",
        Network: "NETWORK",
        Database: "DATABASE",
        ExternalService: "EXTERNAL_SERVICE",
        UnknownError: "UNKNOWN_ERROR",
        Resource: "RESOURCE",
        Authorization: "AUTHORIZATION",
        System: "SYSTEM",
    } as const;
    export type Category = (typeof Category)[keyof typeof Category];
}
