// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

export interface UpdateNetworkBodyDto {
    name?: string;
    rpcHttpUrl?: string;
    rpcWsUrl?: string;
    /** RPC username for Basic Auth (e.g., Bitcoin RPC) */
    rpcUsername?: string;
    /** RPC password for Basic Auth (e.g., Bitcoin RPC) */
    rpcPassword?: string;
    chainId?: number;
    decimals?: number;
    slip44CoinType?: number;
    isMainnet?: boolean;
    /** Address family (EVM, BITCOIN, MOVE, etc.) */
    addressFamily?: OumlaSdkApi.AddressFamily;
    explorerUrl?: string;
    explorerWsUrl?: string;
    enabled?: boolean;
    /** If true, all organizations can access this network without explicit assignment */
    globalAccess?: boolean;
}
