// This file was auto-generated by Fern from our API Definition.

export interface WalletDataDto {
    id: string;
    date?: string;
    organizationId: string;
    reference: string;
    type: string;
    networkId: string;
    currentDeepIndex?: number;
    index: number;
    path?: string;
}
