// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../index.js";

/**
 * Wallet response object
 */
export interface WalletResponse {
    data?: OumlaSdkApi.WalletData;
}
