// This file was auto-generated by Fern from our API Definition.

export interface WalletDataDto {
    /** Wallet UUID */
    id: string;
    /** Wallet creation timestamp */
    date?: string;
    /** Owning organization UUID */
    organizationId: string;
    /** Profile reference that owns this wallet */
    reference: string;
    /** Profile type (User | Department | Merchant) */
    type: string;
    /** Network UUID */
    networkId: string;
    currentDeepIndex?: number;
    index: number;
}
