// This file was auto-generated by Fern from our API Definition.

/**
 * Wallet data object
 */
export interface WalletData {
    id?: string;
    date?: string;
    organizationId?: string;
    reference?: string;
    type?: string;
    network?: WalletData.Network;
    currentDeepIndex?: number;
    index?: number;
    path?: string;
}

export namespace WalletData {
    export const Network = {
        TBtc: "tBTC",
        TEth: "tETH",
        Avax: "AVAX",
        Fuji: "FUJI",
        Sandbox: "SANDBOX",
    } as const;
    export type Network = (typeof Network)[keyof typeof Network];
}
