// This file was auto-generated by Fern from our API Definition.

/**
 * Withdraw response object
 */
export interface WithdrawResponse {
    data?: WithdrawResponse.Data;
}

export namespace WithdrawResponse {
    export interface Data {
        id?: string;
        status?: string;
        hash?: string;
    }
}
