// This file was auto-generated by Fern from our API Definition.

export interface WorkflowStartResultDto {
    /**workflow ID */
    workflowId: string;
    /** Operation ID (e.g. deploymentId, collectionId, mintId, writeCallId) */
    operationId: string;
    /** Workflow status */
    status: WorkflowStartResultDto.Status;
    /** Human-readable status message */
    message: string;
}

export namespace WorkflowStartResultDto {
    /** Workflow status */
    export const Status = {
        Started: "started",
        AlreadyRunning: "already_running",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
