// This file was auto-generated by Fern from our API Definition.

export const GetNativeBalanceRequestNetwork = {
    TBtc: "tBTC",
    TEth: "tETH",
    Avax: "AVAX",
    Fuji: "FUJI",
    Sandbox: "SANDBOX",
} as const;
export type GetNativeBalanceRequestNetwork =
    (typeof GetNativeBalanceRequestNetwork)[keyof typeof GetNativeBalanceRequestNetwork];
