// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         description: "description",
 *         abi: [{
 *                 "key": "value"
 *             }],
 *         bytecode: "bytecode"
 *     }
 */
export interface CreateContractTemplateRequest {
    /** Contract template name */
    name: string;
    /** Contract template description */
    description: string;
    /** Contract ABI */
    abi: Record<string, unknown>[];
    /** Contract bytecode */
    bytecode: string;
    /** Long description of the contract */
    longDescription?: string;
    /** Contract source code */
    sourceCode?: string;
    /** Contract type */
    type?: string;
    /** Contract documentation */
    docs?: CreateContractTemplateRequest.Docs;
    /** Contract attributes */
    attributes?: CreateContractTemplateRequest.Attributes;
}

export namespace CreateContractTemplateRequest {
    /**
     * Contract documentation
     */
    export interface Docs {
        details?: string;
        events?: string;
        kind?: Docs.Kind;
        methods?: Docs.Methods.Item[];
        version?: string;
    }

    export namespace Docs {
        export const Kind = {
            Dev: "dev",
            User: "user",
        } as const;
        export type Kind = (typeof Kind)[keyof typeof Kind];
        export type Methods = Methods.Item[];

        export namespace Methods {
            export interface Item {
                name?: string;
                description?: string;
                params?: Record<string, unknown>;
                returns?: Record<string, unknown>;
            }
        }
    }

    /**
     * Contract attributes
     */
    export interface Attributes {
        useCases?: string[];
        standards?: string[];
        auditor?: Attributes.Auditor;
    }

    export namespace Attributes {
        export interface Auditor {
            name?: string;
            imageURL?: string;
            link?: string;
        }
    }
}
