// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../../../../index.js";

/**
 * @example
 *     {
 *         networkId: "networkId",
 *         addressId: "addressId",
 *         clientShare: "clientShare"
 *     }
 */
export interface DeployContractRequestBodyDto {
    networkId: string;
    addressId: string;
    clientShare: string;
    constructorParameters?: OumlaSdkApi.ConstructorParameterDto[];
}
