// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         network: "network",
 *         addressId: "addressId",
 *         clientShare: "clientShare"
 *     }
 */
export interface DeployContractRequest {
    network: string;
    addressId: string;
    clientShare: string;
    constructorParameters?: Record<string, unknown>[];
}
