// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         functionSignature: "functionSignature"
 *     }
 */
export interface GetTemplateFunctionsRequest {
    /** Function signature to filter by */
    functionSignature?: string;
}
