// This file was auto-generated by Fern from our API Definition.

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as OumlaSdkApi from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace ContractInteractions {
    export interface Options {
        environment?: core.Supplier<environments.OumlaSdkApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Override the x-api-key header */
        apiKey: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Override the x-api-key header */
        apiKey?: string;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

/**
 * Smart contract interaction operations
 */
export class ContractInteractions {
    protected readonly _options: ContractInteractions.Options;

    constructor(_options: ContractInteractions.Options) {
        this._options = _options;
    }

    /**
     * Get ABI functions for a deployed contract
     *
     * @param {OumlaSdkApi.GetDeployedContractAbiRequestNetwork} network - Network
     * @param {string} contractAddress - Contract address
     * @param {ContractInteractions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.contractInteractions.getDeployedContractAbi("tBTC", "contractAddress")
     */
    public getDeployedContractAbi(
        network: OumlaSdkApi.GetDeployedContractAbiRequestNetwork,
        contractAddress: string,
        requestOptions?: ContractInteractions.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.ContractAbiResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__getDeployedContractAbi(network, contractAddress, requestOptions),
        );
    }

    private async __getDeployedContractAbi(
        network: OumlaSdkApi.GetDeployedContractAbiRequestNetwork,
        contractAddress: string,
        requestOptions?: ContractInteractions.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.ContractAbiResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/contract-interactions/network/${encodeURIComponent(network)}/contract-address/${encodeURIComponent(contractAddress)}/functions`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.ContractAbiResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new OumlaSdkApi.NotFoundError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new OumlaSdkApi.InternalServerError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/contract-interactions/network/{network}/contract-address/{contractAddress}/functions.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Call a read-only contract function
     *
     * @param {OumlaSdkApi.ReadCallFunctionRequestNetwork} network - Network
     * @param {string} contractAddress - Contract address
     * @param {OumlaSdkApi.ReadCallFunctionRequest} request
     * @param {ContractInteractions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.contractInteractions.readCallFunction("tBTC", "contractAddress", {
     *         abiFunction: {
     *             "key": "value"
     *         }
     *     })
     */
    public readCallFunction(
        network: OumlaSdkApi.ReadCallFunctionRequestNetwork,
        contractAddress: string,
        request: OumlaSdkApi.ReadCallFunctionRequest,
        requestOptions?: ContractInteractions.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.ReadCallFunctionResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__readCallFunction(network, contractAddress, request, requestOptions),
        );
    }

    private async __readCallFunction(
        network: OumlaSdkApi.ReadCallFunctionRequestNetwork,
        contractAddress: string,
        request: OumlaSdkApi.ReadCallFunctionRequest,
        requestOptions?: ContractInteractions.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.ReadCallFunctionResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/contract-interactions/network/${encodeURIComponent(network)}/contract-address/${encodeURIComponent(contractAddress)}/functions/read`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.ReadCallFunctionResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new OumlaSdkApi.NotFoundError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new OumlaSdkApi.InternalServerError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/contract-interactions/network/{network}/contract-address/{contractAddress}/functions/read.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Call a write contract function (transaction)
     *
     * @param {OumlaSdkApi.WriteCallFunctionRequestNetwork} network - Network
     * @param {string} contractAddress - Contract address
     * @param {OumlaSdkApi.WriteCallFunctionRequest} request
     * @param {ContractInteractions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.ConflictError}
     * @throws {@link OumlaSdkApi.UnprocessableEntityError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     * @throws {@link OumlaSdkApi.BadGatewayError}
     * @throws {@link OumlaSdkApi.ServiceUnavailableError}
     * @throws {@link OumlaSdkApi.GatewayTimeoutError}
     *
     * @example
     *     await client.contractInteractions.writeCallFunction("tBTC", "contractAddress", {
     *         addressId: "addressId",
     *         clientShare: "clientShare",
     *         abiFunction: {
     *             "key": "value"
     *         }
     *     })
     */
    public writeCallFunction(
        network: OumlaSdkApi.WriteCallFunctionRequestNetwork,
        contractAddress: string,
        request: OumlaSdkApi.WriteCallFunctionRequest,
        requestOptions?: ContractInteractions.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.WriteCallFunctionResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__writeCallFunction(network, contractAddress, request, requestOptions),
        );
    }

    private async __writeCallFunction(
        network: OumlaSdkApi.WriteCallFunctionRequestNetwork,
        contractAddress: string,
        request: OumlaSdkApi.WriteCallFunctionRequest,
        requestOptions?: ContractInteractions.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.WriteCallFunctionResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/contract-interactions/network/${encodeURIComponent(network)}/contract-address/${encodeURIComponent(contractAddress)}/functions/write`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.WriteCallFunctionResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new OumlaSdkApi.NotFoundError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new OumlaSdkApi.ConflictError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new OumlaSdkApi.UnprocessableEntityError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new OumlaSdkApi.InternalServerError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 502:
                    throw new OumlaSdkApi.BadGatewayError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 503:
                    throw new OumlaSdkApi.ServiceUnavailableError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 504:
                    throw new OumlaSdkApi.GatewayTimeoutError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/contract-interactions/network/{network}/contract-address/{contractAddress}/functions/write.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get transaction receipt by network and transaction ID
     *
     * @param {OumlaSdkApi.GetTransactionReceiptRequestNetwork} network - Network
     * @param {string} txId - Transaction ID
     * @param {ContractInteractions.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.contractInteractions.getTransactionReceipt("tBTC", "txId")
     */
    public getTransactionReceipt(
        network: OumlaSdkApi.GetTransactionReceiptRequestNetwork,
        txId: string,
        requestOptions?: ContractInteractions.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.TransactionReceiptResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTransactionReceipt(network, txId, requestOptions));
    }

    private async __getTransactionReceipt(
        network: OumlaSdkApi.GetTransactionReceiptRequestNetwork,
        txId: string,
        requestOptions?: ContractInteractions.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.TransactionReceiptResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/contract-interactions/network/${encodeURIComponent(network)}/tx/${encodeURIComponent(txId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.TransactionReceiptResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new OumlaSdkApi.NotFoundError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new OumlaSdkApi.InternalServerError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/contract-interactions/network/{network}/tx/{txId}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
