// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         reference: "user-123",
 *         type: "User"
 *     }
 */
export interface CreateProfileRequest {
    /** Profile reference identifier */
    reference: string;
    /** Profile type */
    type: CreateProfileRequest.Type;
}

export namespace CreateProfileRequest {
    /** Profile type */
    export const Type = {
        User: "User",
        Department: "Department",
        Merchant: "Merchant",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
