// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         reference: "reference",
 *         type: "type"
 *     }
 */
export interface CreateProfileRequestBodyDto {
    reference: string;
    type: string;
}
