// This file was auto-generated by Fern from our API Definition.

export interface DeployContractResponse {
    contractFunction?: DeployContractResponse.ContractFunction;
}

export namespace DeployContractResponse {
    export interface ContractFunction {
        workflowId?: string;
        status?: string;
    }
}
