// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         addressId: "addressId",
 *         clientShare: "clientShare",
 *         tokenId: "tokenId"
 *     }
 */
export interface BurnTokenRequest {
    addressId: string;
    clientShare: string;
    tokenId: string;
    useGasless?: boolean;
    fee?: string;
    feeLevel?: string;
}
