// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         addressId: "addressId",
 *         clientShare: "clientShare",
 *         tokenId: "tokenId"
 *     }
 */
export interface BurnTokenBodyDto {
    addressId: string;
    clientShare: string;
    tokenId: string;
    amount?: string;
    from?: string;
}
