// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         network: "network",
 *         addressId: "addressId",
 *         clientShare: "clientShare",
 *         createParams: {
 *             "key": "value"
 *         },
 *         deploymentId: "deploymentId"
 *     }
 */
export interface CreateCollectionRequest {
    network: string;
    addressId: string;
    clientShare: string;
    createParams: Record<string, unknown>;
    metadata?: Record<string, unknown>;
    displayName?: string;
    deploymentId: string;
    useGasless?: boolean;
    fee?: string;
    feeLevel?: string;
}
