// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../../../../index.js";

/**
 * @example
 *     {
 *         networkId: "networkId",
 *         addressId: "addressId",
 *         type: "NON_FUNGIBLE_TOKEN",
 *         clientShare: "clientShare",
 *         createParams: {
 *             initializeParams: [{
 *                     name: "name",
 *                     type: "type",
 *                     value: "value"
 *                 }]
 *         }
 *     }
 */
export interface CreateCollectionBodyDto {
    networkId: string;
    addressId: string;
    type: CreateCollectionBodyDto.Type;
    clientShare: string;
    createParams: OumlaSdkApi.CreateParams;
    displayName?: string;
    useGasless?: boolean;
    fee?: string;
    feeLevel?: CreateCollectionBodyDto.FeeLevel;
    description?: string;
}

export namespace CreateCollectionBodyDto {
    export const Type = {
        NonFungibleToken: "NON_FUNGIBLE_TOKEN",
        SemiFungibleToken: "SEMI_FUNGIBLE_TOKEN",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const FeeLevel = {
        Low: "LOW",
        Medium: "MEDIUM",
        High: "HIGH",
    } as const;
    export type FeeLevel = (typeof FeeLevel)[keyof typeof FeeLevel];
}
