// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         skip: 1,
 *         take: 1
 *     }
 */
export interface GetCollectionsRequest {
    /** Number of records to skip */
    skip?: number;
    /** Number of records to take */
    take?: number;
}
