// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         type: "type",
 *         skip: 1,
 *         take: 1
 *     }
 */
export interface GetCollectionTokensRequest {
    /** Collection ID */
    id?: string;
    /** Token type */
    type?: string;
    /** Number of records to skip */
    skip?: number;
    /** Number of records to take */
    take?: number;
}
