// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../../../../index.js";

/**
 * @example
 *     {
 *         skip: 0,
 *         take: 25,
 *         id: "id",
 *         type: "MINT"
 *     }
 */
export interface GetCollectionTokensRequest {
    skip?: number;
    take?: number;
    id: string;
    type?: OumlaSdkApi.GetCollectionTokensRequestType;
}
