// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         skip: 0,
 *         take: 25
 *     }
 */
export interface GetTokensRequest {
    skip?: number;
    take?: number;
}
