// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../../../../index.js";

/**
 * @example
 *     {
 *         networkId: "networkId",
 *         addressId: "addressId",
 *         clientShare: "clientShare",
 *         createParams: {
 *             initializeParams: [{
 *                     name: "name",
 *                     type: "type",
 *                     value: "value"
 *                 }]
 *         },
 *         deploymentId: "deploymentId",
 *         displayName: "displayName",
 *         useGasless: true,
 *         fee: "fee"
 *     }
 */
export interface IssueNewTokenRequestBody {
    networkId: string;
    addressId: string;
    clientShare: string;
    createParams: OumlaSdkApi.CreateParams;
    deploymentId: string;
    displayName: string;
    useGasless: boolean;
    fee: string;
    feeLevel?: IssueNewTokenRequestBody.FeeLevel;
}

export namespace IssueNewTokenRequestBody {
    export const FeeLevel = {
        Low: "LOW",
        Medium: "MEDIUM",
        High: "HIGH",
    } as const;
    export type FeeLevel = (typeof FeeLevel)[keyof typeof FeeLevel];
}
