// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         addressId: "addressId",
 *         clientShare: "clientShare",
 *         deploymentId: "deploymentId",
 *         createParams: {
 *             initializeParams: [{
 *                     name: "name",
 *                     type: "type",
 *                     value: "value"
 *                 }]
 *         }
 *     }
 */
export interface IssueNewTokenRequest {
    /** Blockchain network */
    network?: string;
    /** Address ID for token creation */
    addressId: string;
    /** Client share for signing */
    clientShare: string;
    /** Deployed contract ID */
    deploymentId: string;
    createParams: IssueNewTokenRequest.CreateParams;
    /** Token display name */
    displayName?: string;
    /** Use gasless transaction */
    useGasless?: boolean;
    /** Transaction fee */
    fee?: string;
    /** Fee level */
    feeLevel?: string;
}

export namespace IssueNewTokenRequest {
    export interface CreateParams {
        /** Initialize parameters */
        initializeParams: CreateParams.InitializeParams.Item[];
    }

    export namespace CreateParams {
        export type InitializeParams = InitializeParams.Item[];

        export namespace InitializeParams {
            export interface Item {
                /** Parameter name */
                name: string;
                /** Parameter type */
                type: string;
                /** Parameter value */
                value: string;
            }
        }
    }
}
