// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contractAddress: "contractAddress"
 *     }
 */
export interface LinkContractRequest {
    /** Contract type */
    type?: string;
    /** Reference ID */
    refId?: string;
    /** Display name */
    displayName?: string;
    /** Blockchain network */
    network?: string;
    /** Contract address */
    contractAddress: string;
}
