// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contractAddress: "contractAddress"
 *     }
 */
export interface LinkContractRequest {
    contractAddress: string;
    network?: string;
    displayName?: string;
    refId?: string;
    type?: string;
}
