// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         networkId: "networkId",
 *         contractAddress: "contractAddress"
 *     }
 */
export interface LinkContractBodyDto {
    type?: string;
    refId?: string;
    displayName?: string;
    networkId: string;
    contractAddress: string;
}
