// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         addressId: "addressId",
 *         clientShare: "clientShare",
 *         to: "to"
 *     }
 */
export interface MintTokenRequest {
    addressId: string;
    clientShare: string;
    to: string;
    metadata?: Record<string, unknown>;
    useGasless?: boolean;
    fee?: string;
    feeLevel?: string;
}
