// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../../../../index.js";

/**
 * @example
 *     {
 *         addressId: "addressId",
 *         clientShare: "clientShare",
 *         to: "to",
 *         tokenId: "tokenId"
 *     }
 */
export interface MintTokenBodyDto {
    addressId: string;
    clientShare: string;
    to: string;
    tokenId: string;
    amount?: string;
    /** Required if metadata is not provided */
    metadataURI?: string;
    /** Required if metadataURI is not provided */
    metadata?: OumlaSdkApi.MetadataDto;
}
