// This file was auto-generated by Fern from our API Definition.

export const GetDeployedContractsRequestNetwork = {
    TBtc: "tBTC",
    TEth: "tETH",
    Avax: "AVAX",
    Fuji: "FUJI",
    Sandbox: "SANDBOX",
} as const;
export type GetDeployedContractsRequestNetwork =
    (typeof GetDeployedContractsRequestNetwork)[keyof typeof GetDeployedContractsRequestNetwork];
