// This file was auto-generated by Fern from our API Definition.

export const GetDeployedContractsRequestNetwork = {
    Btc: "BTC",
    TBtc: "tBTC",
    Eth: "ETH",
    TEth: "tETH",
} as const;
export type GetDeployedContractsRequestNetwork =
    (typeof GetDeployedContractsRequestNetwork)[keyof typeof GetDeployedContractsRequestNetwork];
