// This file was auto-generated by Fern from our API Definition.

export const GetDeployedContractByAddressRequestNetwork = {
    TBtc: "tBTC",
    TEth: "tETH",
    Avax: "AVAX",
    Fuji: "FUJI",
    Sandbox: "SANDBOX",
} as const;
export type GetDeployedContractByAddressRequestNetwork =
    (typeof GetDeployedContractByAddressRequestNetwork)[keyof typeof GetDeployedContractByAddressRequestNetwork];
