// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         skip: 0,
 *         take: 10,
 *         address: "address",
 *         walletId: "walletId",
 *         contractAddress: "contractAddress",
 *         tokenizationId: "tokenizationId",
 *         network: "network"
 *     }
 */
export interface GetAssetsRequest {
    skip: number;
    take: number;
    address: string;
    walletId?: string;
    contractAddress?: string;
    tokenizationId?: string;
    network?: string;
}
