// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         skip: 0,
 *         take: 10,
 *         networkId: "networkId",
 *         address: "address",
 *         walletId: "walletId",
 *         network: "network"
 *     }
 */
export interface GetNativeBalanceRequest {
    skip: number;
    take: number;
    networkId?: string;
    address: string;
    walletId?: string;
    network?: string;
}
