// This file was auto-generated by Fern from our API Definition.

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as OumlaSdkApi from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Profiles {
    export interface Options {
        environment?: core.Supplier<environments.OumlaSdkApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Override the x-api-key header */
        apiKey: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Override the x-api-key header */
        apiKey?: string;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

/**
 * User profile management
 */
export class Profiles {
    protected readonly _options: Profiles.Options;

    constructor(_options: Profiles.Options) {
        this._options = _options;
    }

    /**
     * Get list of profiles with pagination
     *
     * @param {OumlaSdkApi.GetProfilesRequest} request
     * @param {Profiles.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.profiles.getProfiles({
     *         skip: 1,
     *         take: 1
     *     })
     */
    public getProfiles(
        request: OumlaSdkApi.GetProfilesRequest = {},
        requestOptions?: Profiles.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.ProfilesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getProfiles(request, requestOptions));
    }

    private async __getProfiles(
        request: OumlaSdkApi.GetProfilesRequest = {},
        requestOptions?: Profiles.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.ProfilesResponse>> {
        const { skip, take } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (take != null) {
            _queryParams["take"] = take.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/profiles",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.ProfilesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new OumlaSdkApi.InternalServerError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError("Timeout exceeded when calling GET /api/v1/profiles.");
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new user profile
     *
     * @param {OumlaSdkApi.CreateProfileRequest} request
     * @param {Profiles.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.ConflictError}
     * @throws {@link OumlaSdkApi.UnprocessableEntityError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.profiles.createProfile({
     *         reference: "user-123",
     *         type: "User"
     *     })
     */
    public createProfile(
        request: OumlaSdkApi.CreateProfileRequest,
        requestOptions?: Profiles.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.ProfileResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createProfile(request, requestOptions));
    }

    private async __createProfile(
        request: OumlaSdkApi.CreateProfileRequest,
        requestOptions?: Profiles.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.ProfileResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/profiles",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.ProfileResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new OumlaSdkApi.ConflictError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new OumlaSdkApi.UnprocessableEntityError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new OumlaSdkApi.InternalServerError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError("Timeout exceeded when calling POST /api/v1/profiles.");
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
