// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         abiFunction: {
 *             name: "name",
 *             inputs: [{}],
 *             outputs: [{}],
 *             type: "type"
 *         }
 *     }
 */
export interface ReadFunctionRequest {
    /** ABI function definition */
    abiFunction: ReadFunctionRequest.AbiFunction;
}

export namespace ReadFunctionRequest {
    /**
     * ABI function definition
     */
    export interface AbiFunction {
        /** Function name */
        name: string;
        /** Function input parameters */
        inputs: AbiFunction.Inputs.Item[];
        /** Function output parameters */
        outputs: AbiFunction.Outputs.Item[];
        stateMutability?: string;
        type: string;
    }

    export namespace AbiFunction {
        export type Inputs = Inputs.Item[];

        export namespace Inputs {
            export interface Item {
                name?: string;
                type?: string;
                internalType?: string;
            }
        }

        export type Outputs = Outputs.Item[];

        export namespace Outputs {
            export interface Item {
                name?: string;
                type?: string;
                internalType?: string;
            }
        }
    }
}
