// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         abiFunction: {
 *             "key": "value"
 *         }
 *     }
 */
export interface ReadCallFunctionRequest {
    abiFunction: Record<string, unknown>;
}
