// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../../../../index.js";

/**
 * @example
 *     {
 *         abiFunction: {
 *             type: "function",
 *             inputs: [{
 *                     name: "name",
 *                     type: "type",
 *                     value: {
 *                         "key": "value"
 *                     }
 *                 }]
 *         }
 *     }
 */
export interface ReadCallFunctionBody {
    abiFunction: OumlaSdkApi.ContractFunDto;
}
