// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../../../../index.js";

/**
 * @example
 *     {
 *         addressId: "addressId",
 *         clientShare: "clientShare",
 *         abiFunction: {
 *             type: "function",
 *             inputs: [{
 *                     name: "name",
 *                     type: "type",
 *                     value: {
 *                         "key": "value"
 *                     }
 *                 }]
 *         }
 *     }
 */
export interface WriteCallFunctionBody {
    addressId: string;
    clientShare: string;
    abiFunction: OumlaSdkApi.ContractFunDto;
    amount?: string;
    feeLevel?: WriteCallFunctionBody.FeeLevel;
}

export namespace WriteCallFunctionBody {
    export const FeeLevel = {
        Low: "LOW",
        Medium: "MEDIUM",
        High: "HIGH",
    } as const;
    export type FeeLevel = (typeof FeeLevel)[keyof typeof FeeLevel];
}
