// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         addressId: "addressId",
 *         clientShare: "clientShare",
 *         abiFunction: {
 *             "key": "value"
 *         }
 *     }
 */
export interface WriteCallFunctionRequest {
    addressId: string;
    clientShare: string;
    abiFunction: Record<string, unknown>;
    amount?: string;
    feeLevel?: string;
}
