// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         addressId: "addressId",
 *         clientShare: "clientShare",
 *         abiFunction: {
 *             name: "name",
 *             inputs: [{}],
 *             outputs: [{}],
 *             type: "type"
 *         }
 *     }
 */
export interface WriteFunctionRequest {
    /** Address ID for transaction */
    addressId: string;
    /** Client share for signing */
    clientShare: string;
    /** ABI function definition */
    abiFunction: WriteFunctionRequest.AbiFunction;
    /** ETH value to send */
    amount?: string;
    /** Fee level for transaction */
    feeLevel?: WriteFunctionRequest.FeeLevel;
}

export namespace WriteFunctionRequest {
    /**
     * ABI function definition
     */
    export interface AbiFunction {
        /** Function name */
        name: string;
        /** Function input parameters */
        inputs: AbiFunction.Inputs.Item[];
        /** Function output parameters */
        outputs: AbiFunction.Outputs.Item[];
        stateMutability?: string;
        type: string;
    }

    export namespace AbiFunction {
        export type Inputs = Inputs.Item[];

        export namespace Inputs {
            export interface Item {
                name?: string;
                type?: string;
                internalType?: string;
            }
        }

        export type Outputs = Outputs.Item[];

        export namespace Outputs {
            export interface Item {
                name?: string;
                type?: string;
                internalType?: string;
            }
        }
    }

    /** Fee level for transaction */
    export const FeeLevel = {
        Low: "LOW",
        Medium: "MEDIUM",
        High: "HIGH",
    } as const;
    export type FeeLevel = (typeof FeeLevel)[keyof typeof FeeLevel];
}
