// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         to: "to",
 *         amount: "amount",
 *         from: ["from"],
 *         networkId: "networkId",
 *         clientShare: "clientShare"
 *     }
 */
export interface CreateWithdrawRequestBodyDto {
    to: string;
    amount: string;
    /** Input UTXOs or addresses */
    from: string[];
    networkId: string;
    clientShare: string;
}
