// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         to: "to",
 *         amount: "amount",
 *         from: ["from"],
 *         network: "BTC",
 *         clientShare: "clientShare"
 *     }
 */
export interface CreateWithdrawalRequest {
    /** Recipient address for withdrawal */
    to: string;
    /** Withdrawal amount */
    amount: string;
    /** Array of source addresses for withdrawal */
    from: string[];
    /** Blockchain network */
    network: CreateWithdrawalRequest.Network;
    /** Client share for signing */
    clientShare: string;
}

export namespace CreateWithdrawalRequest {
    /** Blockchain network */
    export const Network = {
        Btc: "BTC",
        TBtc: "tBTC",
        Eth: "ETH",
        TEth: "tETH",
    } as const;
    export type Network = (typeof Network)[keyof typeof Network];
}
