// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         to: "to",
 *         amount: "amount",
 *         from: ["from"],
 *         network: "tBTC",
 *         clientShare: "clientShare"
 *     }
 */
export interface CreateWithdrawRequest {
    to: string;
    amount: string;
    from: string[];
    network: CreateWithdrawRequest.Network;
    clientShare: string;
}

export namespace CreateWithdrawRequest {
    export const Network = {
        TBtc: "tBTC",
        TEth: "tETH",
        Avax: "AVAX",
        Fuji: "FUJI",
        Sandbox: "SANDBOX",
    } as const;
    export type Network = (typeof Network)[keyof typeof Network];
}
