// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         reference: "reference",
 *         network: "BTC"
 *     }
 */
export interface CreateWalletRequest {
    /** Profile reference */
    reference: string;
    /** Blockchain network */
    network: CreateWalletRequest.Network;
}

export namespace CreateWalletRequest {
    /** Blockchain network */
    export const Network = {
        TBtc: "tBTC",
        TEth: "tETH",
    } as const;
    export type Network = (typeof Network)[keyof typeof Network];
}
