// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         network: "network",
 *         contractAddress: "contractAddress",
 *         name: "name",
 *         abi: [{
 *                 "key": "value"
 *             }]
 *     }
 */
export interface AddContractAbiRequest {
    /** Blockchain network */
    network: string;
    /** Contract address */
    contractAddress: string;
    /** Contract name */
    name: string;
    /** Contract ABI */
    abi: Record<string, unknown>[];
}
