// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contractAddress: "contractAddress",
 *         network: "network"
 *     }
 */
export interface FetchContractAbiRequest {
    contractAddress: string;
    network: string;
}
