// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../../../../index.js";

/**
 * @example
 *     {
 *         contractAddress: "contractAddress",
 *         network: "tBTC",
 *         contractTemplateId: "contractTemplateId",
 *         skip: 1,
 *         take: 1
 *     }
 */
export interface GetDeployedContractsRequest {
    /** Contract address filter */
    contractAddress?: string;
    /** Network filter */
    network?: OumlaSdkApi.GetDeployedContractsRequestNetwork;
    /** Contract template ID filter */
    contractTemplateId?: string;
    /** Number of records to skip */
    skip?: number;
    /** Number of records to take */
    take?: number;
}
