// This file was auto-generated by Fern from our API Definition.

import * as OumlaSdkApi from "../../../../index.js";

/**
 * @example
 *     {
 *         skip: 1,
 *         take: 1,
 *         contractAddress: "contractAddress",
 *         network: "BTC",
 *         contractTemplateId: "contractTemplateId"
 *     }
 */
export interface GetDeployedContractsRequest {
    /** Number of records to skip */
    skip?: number;
    /** Number of records to take */
    take?: number;
    /** Filter by contract address */
    contractAddress?: string;
    /** Filter by blockchain network */
    network?: OumlaSdkApi.GetDeployedContractsRequestNetwork;
    /** Filter by contract template ID */
    contractTemplateId?: string;
}
