// This file was auto-generated by Fern from our API Definition.

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as OumlaSdkApi from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Tokenization {
    export interface Options {
        environment?: core.Supplier<environments.OumlaSdkApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class Tokenization {
    protected readonly _options: Tokenization.Options;

    constructor(_options: Tokenization.Options) {
        this._options = _options;
    }

    /**
     * List issued tokens for the organization with pagination.
     *
     * @param {OumlaSdkApi.GetTokensRequest} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.getTokens({
     *         skip: 0,
     *         take: 25
     *     })
     */
    public getTokens(
        request: OumlaSdkApi.GetTokensRequest = {},
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetTokensResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getTokens(request, requestOptions));
    }

    private async __getTokens(
        request: OumlaSdkApi.GetTokensRequest = {},
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetTokensResponseDto>> {
        const { skip, take } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (take != null) {
            _queryParams["take"] = take.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/tokens",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.GetTokensResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/tokenization/tokens.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Issue a new token from a deployed contract template.
     *
     * @param {OumlaSdkApi.IssueNewTokenRequestBody} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.issueNewToken({
     *         networkId: "networkId",
     *         addressId: "addressId",
     *         clientShare: "clientShare",
     *         createParams: {
     *             initializeParams: [{
     *                     name: "name",
     *                     type: "type",
     *                     value: "value"
     *                 }]
     *         },
     *         deploymentId: "deploymentId",
     *         displayName: "displayName",
     *         useGasless: true,
     *         fee: "fee"
     *     })
     */
    public issueNewToken(
        request: OumlaSdkApi.IssueNewTokenRequestBody,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.IssueTokenResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__issueNewToken(request, requestOptions));
    }

    private async __issueNewToken(
        request: OumlaSdkApi.IssueNewTokenRequestBody,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.IssueTokenResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/tokens",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.IssueTokenResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/tokenization/tokens.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Link an existing deployed contract to the organization for tokenization.
     *
     * @param {OumlaSdkApi.LinkContractBodyDto} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.ConflictError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.linkContract({
     *         networkId: "networkId",
     *         contractAddress: "contractAddress"
     *     })
     */
    public linkContract(
        request: OumlaSdkApi.LinkContractBodyDto,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.LinkContractResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__linkContract(request, requestOptions));
    }

    private async __linkContract(
        request: OumlaSdkApi.LinkContractBodyDto,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.LinkContractResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/tokens/link",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.LinkContractResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new OumlaSdkApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/tokenization/tokens/link.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List tokenization collections for the organization with pagination.
     *
     * @param {OumlaSdkApi.GetCollectionsRequest} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.getCollections({
     *         skip: 0,
     *         take: 25
     *     })
     */
    public getCollections(
        request: OumlaSdkApi.GetCollectionsRequest = {},
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetCollectionsResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getCollections(request, requestOptions));
    }

    private async __getCollections(
        request: OumlaSdkApi.GetCollectionsRequest = {},
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetCollectionsResponseDto>> {
        const { skip, take } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (take != null) {
            _queryParams["take"] = take.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/collections",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetCollectionsResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/tokenization/collections.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Start the create-collection workflow. Returns workflow ID; collection is created asynchronously.
     *
     * @param {OumlaSdkApi.CreateCollectionBodyDto} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.createCollection({
     *         networkId: "networkId",
     *         addressId: "addressId",
     *         type: "NON_FUNGIBLE_TOKEN",
     *         clientShare: "clientShare",
     *         createParams: {
     *             initializeParams: [{
     *                     name: "name",
     *                     type: "type",
     *                     value: "value"
     *                 }]
     *         }
     *     })
     */
    public createCollection(
        request: OumlaSdkApi.CreateCollectionBodyDto,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.CreateCollectionWorkflowResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__createCollection(request, requestOptions));
    }

    private async __createCollection(
        request: OumlaSdkApi.CreateCollectionBodyDto,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.CreateCollectionWorkflowResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/collections",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.CreateCollectionWorkflowResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/tokenization/collections.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get a single collection by its ID.
     *
     * @param {string} id - Collection ID
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.getCollectionById("id")
     */
    public getCollectionById(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetCollectionByIdResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getCollectionById(id, requestOptions));
    }

    private async __getCollectionById(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetCollectionByIdResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/collections/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetCollectionByIdResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/tokenization/collections/{id}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete a collection and its associated data.
     *
     * @param {string} id - Collection ID
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.deleteCollection("id")
     */
    public deleteCollection(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.DeleteCollectionResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__deleteCollection(id, requestOptions));
    }

    private async __deleteCollection(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.DeleteCollectionResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/collections/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.DeleteCollectionResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling DELETE /api/v1/tokenization/collections/{id}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get details of a specific token within a collection.
     *
     * @param {string} id - Collection ID
     * @param {string} tokenId - Token ID
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.getCollectionTokenDetails("id", "tokenId")
     */
    public getCollectionTokenDetails(
        id: string,
        tokenId: string,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetCollectionTokenDetailsResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getCollectionTokenDetails(id, tokenId, requestOptions));
    }

    private async __getCollectionTokenDetails(
        id: string,
        tokenId: string,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetCollectionTokenDetailsResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/collections/${encodeURIComponent(id)}/tokens/${encodeURIComponent(tokenId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetCollectionTokenDetailsResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/tokenization/collections/{id}/tokens/{tokenId}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Start mint workflow for a collection. Requires mint policy.
     *
     * @param {string} id - Collection ID
     * @param {OumlaSdkApi.MintTokenBodyDto} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.mintToken("id", {
     *         addressId: "addressId",
     *         clientShare: "clientShare",
     *         to: "to",
     *         tokenId: "tokenId"
     *     })
     */
    public mintToken(
        id: string,
        request: OumlaSdkApi.MintTokenBodyDto,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.MintTokenResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__mintToken(id, request, requestOptions));
    }

    private async __mintToken(
        id: string,
        request: OumlaSdkApi.MintTokenBodyDto,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.MintTokenResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/collections/${encodeURIComponent(id)}/tokens/mint`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.MintTokenResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/tokenization/collections/{id}/tokens/mint.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * List tokens in a collection, optionally filtered by type, with pagination.
     *
     * @param {OumlaSdkApi.GetCollectionTokensRequest} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.getCollectionTokens({
     *         skip: 0,
     *         take: 25,
     *         id: "id",
     *         type: "MINT"
     *     })
     */
    public getCollectionTokens(
        request: OumlaSdkApi.GetCollectionTokensRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetCollectionTokensResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getCollectionTokens(request, requestOptions));
    }

    private async __getCollectionTokens(
        request: OumlaSdkApi.GetCollectionTokensRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetCollectionTokensResponseDto>> {
        const { skip, take, id, type: type_ } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (take != null) {
            _queryParams["take"] = take.toString();
        }

        _queryParams["id"] = id;
        if (type_ != null) {
            _queryParams["type"] = type_;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/collection/tokens",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetCollectionTokensResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/tokenization/collection/tokens.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Start burn workflow for tokens in a collection. Requires burn policy.
     *
     * @param {string} id - Collection ID
     * @param {OumlaSdkApi.BurnTokenBodyDto} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.burnToken("id", {
     *         addressId: "addressId",
     *         clientShare: "clientShare",
     *         tokenId: "tokenId"
     *     })
     */
    public burnToken(
        id: string,
        request: OumlaSdkApi.BurnTokenBodyDto,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.BurnTokenResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__burnToken(id, request, requestOptions));
    }

    private async __burnToken(
        id: string,
        request: OumlaSdkApi.BurnTokenBodyDto,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.BurnTokenResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/collections/${encodeURIComponent(id)}/tokens/burn`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.BurnTokenResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/tokenization/collections/{id}/tokens/burn.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get a linked token by its ID.
     *
     * @param {string} id - Token ID
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.getLinkedToken("id")
     */
    public getLinkedToken(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetLinkedTokenResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getLinkedToken(id, requestOptions));
    }

    private async __getLinkedToken(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetLinkedTokenResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/tokens/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetLinkedTokenResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/tokenization/tokens/{id}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Unlink a token from the organization.
     *
     * @param {string} id - Token ID
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.tokenization.unlinkToken("id")
     */
    public unlinkToken(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.UnlinkTokenResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__unlinkToken(id, requestOptions));
    }

    private async __unlinkToken(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.UnlinkTokenResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/tokens/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.UnlinkTokenResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling DELETE /api/v1/tokenization/tokens/{id}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
