// This file was auto-generated by Fern from our API Definition.

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as OumlaSdkApi from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Tokenization {
    export interface Options {
        environment?: core.Supplier<environments.OumlaSdkApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Override the x-api-key header */
        apiKey: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Override the x-api-key header */
        apiKey?: string;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

/**
 * Token creation, minting, and management
 */
export class Tokenization {
    protected readonly _options: Tokenization.Options;

    constructor(_options: Tokenization.Options) {
        this._options = _options;
    }

    /**
     * Retrieve a paginated list of tokens
     *
     * @param {OumlaSdkApi.GetTokensRequest} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tokenization.getTokens({
     *         skip: 1,
     *         take: 1
     *     })
     */
    public getTokens(
        request: OumlaSdkApi.GetTokensRequest = {},
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.PaginatedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTokens(request, requestOptions));
    }

    private async __getTokens(
        request: OumlaSdkApi.GetTokensRequest = {},
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.PaginatedResponse>> {
        const { skip, take } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (take != null) {
            _queryParams["take"] = take.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/tokens",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.PaginatedResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/tokenization/tokens.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Issue a new token using a contract template
     *
     * @param {OumlaSdkApi.IssueNewTokenRequest} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tokenization.issueNewToken({
     *         addressId: "addressId",
     *         clientShare: "clientShare",
     *         deploymentId: "deploymentId",
     *         createParams: {
     *             initializeParams: [{
     *                     name: "name",
     *                     type: "type",
     *                     value: "value"
     *                 }]
     *         }
     *     })
     */
    public issueNewToken(
        request: OumlaSdkApi.IssueNewTokenRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__issueNewToken(request, requestOptions));
    }

    private async __issueNewToken(
        request: OumlaSdkApi.IssueNewTokenRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/tokens",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/tokenization/tokens.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Link an existing contract to the platform
     *
     * @param {OumlaSdkApi.LinkContractRequest} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tokenization.linkContract({
     *         contractAddress: "contractAddress"
     *     })
     */
    public linkContract(
        request: OumlaSdkApi.LinkContractRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__linkContract(request, requestOptions));
    }

    private async __linkContract(
        request: OumlaSdkApi.LinkContractRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/tokens/link",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/tokenization/tokens/link.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a paginated list of collections
     *
     * @param {OumlaSdkApi.GetCollectionsRequest} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tokenization.getCollections({
     *         skip: 1,
     *         take: 1
     *     })
     */
    public getCollections(
        request: OumlaSdkApi.GetCollectionsRequest = {},
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.PaginatedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getCollections(request, requestOptions));
    }

    private async __getCollections(
        request: OumlaSdkApi.GetCollectionsRequest = {},
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.PaginatedResponse>> {
        const { skip, take } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (take != null) {
            _queryParams["take"] = take.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/collections",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.PaginatedResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/tokenization/collections.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new token collection
     *
     * @param {OumlaSdkApi.CreateCollectionRequest} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tokenization.createCollection({
     *         type: "NON_FUNGIBLE_TOKEN",
     *         addressId: "addressId",
     *         clientShare: "clientShare",
     *         createParams: {
     *             initializeParams: [{
     *                     name: "name",
     *                     type: "type",
     *                     value: "value"
     *                 }]
     *         }
     *     })
     */
    public createCollection(
        request: OumlaSdkApi.CreateCollectionRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createCollection(request, requestOptions));
    }

    private async __createCollection(
        request: OumlaSdkApi.CreateCollectionRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/collections",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/tokenization/collections.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a specific collection
     *
     * @param {string} id - Collection ID
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tokenization.getCollection("id")
     */
    public getCollection(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getCollection(id, requestOptions));
    }

    private async __getCollection(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/collections/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/tokenization/collections/{id}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete a collection
     *
     * @param {string} id - Collection ID
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tokenization.deleteCollection("id")
     */
    public deleteCollection(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteCollection(id, requestOptions));
    }

    private async __deleteCollection(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/collections/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling DELETE /api/v1/tokenization/collections/{id}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve details for a specific token in a collection
     *
     * @param {string} id - Collection ID
     * @param {string} tokenId - Token ID
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tokenization.getCollectionTokenDetails("id", "tokenId")
     */
    public getCollectionTokenDetails(
        id: string,
        tokenId: string,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getCollectionTokenDetails(id, tokenId, requestOptions));
    }

    private async __getCollectionTokenDetails(
        id: string,
        tokenId: string,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/collections/${encodeURIComponent(id)}/tokens/${encodeURIComponent(tokenId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/tokenization/collections/{id}/tokens/{tokenId}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Mint a new token in a collection
     *
     * @param {string} id - Collection ID
     * @param {OumlaSdkApi.MintTokenRequest} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tokenization.mintToken("id", {
     *         addressId: "addressId",
     *         clientShare: "clientShare",
     *         to: "to",
     *         tokenId: "tokenId"
     *     })
     */
    public mintToken(
        id: string,
        request: OumlaSdkApi.MintTokenRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__mintToken(id, request, requestOptions));
    }

    private async __mintToken(
        id: string,
        request: OumlaSdkApi.MintTokenRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/collections/${encodeURIComponent(id)}/tokens/mint`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/tokenization/collections/{id}/tokens/mint.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Burn a token
     *
     * @param {string} id - Collection ID
     * @param {OumlaSdkApi.BurnTokenRequest} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tokenization.burnToken("id", {
     *         addressId: "addressId",
     *         clientShare: "clientShare",
     *         tokenId: "tokenId"
     *     })
     */
    public burnToken(
        id: string,
        request: OumlaSdkApi.BurnTokenRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__burnToken(id, request, requestOptions));
    }

    private async __burnToken(
        id: string,
        request: OumlaSdkApi.BurnTokenRequest,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/collections/${encodeURIComponent(id)}/tokens/burn`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/tokenization/collections/{id}/tokens/burn.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve collection tokens (mints or burns) filtered by collection ID and type
     *
     * @param {OumlaSdkApi.GetCollectionTokensRequest} request
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.NotFoundError}
     *
     * @example
     *     await client.tokenization.getCollectionTokens({
     *         id: "id",
     *         type: "MINT",
     *         skip: 1,
     *         take: 1
     *     })
     */
    public getCollectionTokens(
        request: OumlaSdkApi.GetCollectionTokensRequest = {},
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getCollectionTokens(request, requestOptions));
    }

    private async __getCollectionTokens(
        request: OumlaSdkApi.GetCollectionTokensRequest = {},
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        const { id, type: type_, skip, take } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (id != null) {
            _queryParams["id"] = id;
        }

        if (type_ != null) {
            _queryParams["type"] = type_;
        }

        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (take != null) {
            _queryParams["take"] = take.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/tokenization/collection/tokens",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new OumlaSdkApi.NotFoundError(
                        _response.error.body as OumlaSdkApi.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/tokenization/collection/tokens.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Unlink a token from the platform
     *
     * @param {string} id - Token ID
     * @param {Tokenization.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.tokenization.unlinkToken("id")
     */
    public unlinkToken(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__unlinkToken(id, requestOptions));
    }

    private async __unlinkToken(
        id: string,
        requestOptions?: Tokenization.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/tokenization/tokens/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling DELETE /api/v1/tokenization/tokens/{id}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
