// This file was auto-generated by Fern from our API Definition.

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as OumlaSdkApi from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace ContractTemplates {
    export interface Options {
        environment?: core.Supplier<environments.OumlaSdkApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class ContractTemplates {
    protected readonly _options: ContractTemplates.Options;

    constructor(_options: ContractTemplates.Options) {
        this._options = _options;
    }

    /**
     * List contract templates for the organization with pagination.
     *
     * @param {OumlaSdkApi.GetContractsRequest} request
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.contractTemplates.getContracts({
     *         skip: 0,
     *         take: 10
     *     })
     */
    public getContracts(
        request: OumlaSdkApi.GetContractsRequest = {},
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetContractsResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getContracts(request, requestOptions));
    }

    private async __getContracts(
        request: OumlaSdkApi.GetContractsRequest = {},
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetContractsResponseDto>> {
        const { skip, take } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (take != null) {
            _queryParams["take"] = take.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/contract-templates",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.GetContractsResponseDto, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/contract-templates.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new contract template (ABI, bytecode, metadata).
     *
     * @param {OumlaSdkApi.CreateContractRequestBodyDto} request
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.ConflictError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.contractTemplates.createContract({
     *         name: "name",
     *         description: "description",
     *         bytecode: "bytecode",
     *         abi: [{
     *                 type: "function",
     *                 inputs: [{
     *                         name: "name",
     *                         type: "type",
     *                         value: {
     *                             "key": "value"
     *                         }
     *                     }]
     *             }]
     *     })
     */
    public createContract(
        request: OumlaSdkApi.CreateContractRequestBodyDto,
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.CreateContractResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__createContract(request, requestOptions));
    }

    private async __createContract(
        request: OumlaSdkApi.CreateContractRequestBodyDto,
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.CreateContractResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/contract-templates",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.CreateContractResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new OumlaSdkApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/contract-templates.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get a contract template by its ID.
     *
     * @param {string} templateId - Contract template ID
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.contractTemplates.getContractById("templateId")
     */
    public getContractById(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetContractByIdResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getContractById(templateId, requestOptions));
    }

    private async __getContractById(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetContractByIdResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/contract-templates/${encodeURIComponent(templateId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetContractByIdResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/contract-templates/{templateId}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete a contract template by ID.
     *
     * @param {string} templateId - Contract template ID
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.contractTemplates.deleteContract("templateId")
     */
    public deleteContract(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.DeleteContractResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__deleteContract(templateId, requestOptions));
    }

    private async __deleteContract(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.DeleteContractResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/contract-templates/${encodeURIComponent(templateId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.DeleteContractResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling DELETE /api/v1/contract-templates/{templateId}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get constructor info (params, ABI) for a contract template.
     *
     * @param {string} templateId - Contract template ID
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.contractTemplates.getContractConstructorById("templateId")
     */
    public getContractConstructorById(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetContractConstructorResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getContractConstructorById(templateId, requestOptions));
    }

    private async __getContractConstructorById(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetContractConstructorResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/contract-templates/${encodeURIComponent(templateId)}/getConstructorInfo`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetContractConstructorResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/contract-templates/{templateId}/getConstructorInfo.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get function metadata/ABI for a contract template.
     *
     * @param {string} templateId - Contract template ID
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.contractTemplates.getContractFunctionById("templateId")
     */
    public getContractFunctionById(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetContractFunctionResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getContractFunctionById(templateId, requestOptions));
    }

    private async __getContractFunctionById(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetContractFunctionResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/contract-templates/${encodeURIComponent(templateId)}/function`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetContractFunctionResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/contract-templates/{templateId}/function.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Deploy a contract from a template to the specified network.
     *
     * @param {string} templateId - Contract template ID
     * @param {OumlaSdkApi.DeployContractRequestBodyDto} request
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.contractTemplates.deployContract("templateId", {
     *         networkId: "networkId",
     *         addressId: "addressId",
     *         clientShare: "clientShare"
     *     })
     */
    public deployContract(
        templateId: string,
        request: OumlaSdkApi.DeployContractRequestBodyDto,
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.DeployContractResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__deployContract(templateId, request, requestOptions));
    }

    private async __deployContract(
        templateId: string,
        request: OumlaSdkApi.DeployContractRequestBodyDto,
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.DeployContractResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/contract-templates/${encodeURIComponent(templateId)}/deploy`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.DeployContractResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/contract-templates/{templateId}/deploy.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
