// This file was auto-generated by Fern from our API Definition.

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as OumlaSdkApi from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace ContractTemplates {
    export interface Options {
        environment?: core.Supplier<environments.OumlaSdkApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Override the x-api-key header */
        apiKey: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Override the x-api-key header */
        apiKey?: string;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

/**
 * Smart contract template management
 */
export class ContractTemplates {
    protected readonly _options: ContractTemplates.Options;

    constructor(_options: ContractTemplates.Options) {
        this._options = _options;
    }

    /**
     * Retrieve a paginated list of contract templates
     *
     * @param {OumlaSdkApi.GetContractTemplatesRequest} request
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contractTemplates.getContractTemplates({
     *         skip: 1,
     *         take: 1
     *     })
     */
    public getContractTemplates(
        request: OumlaSdkApi.GetContractTemplatesRequest = {},
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.PaginatedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getContractTemplates(request, requestOptions));
    }

    private async __getContractTemplates(
        request: OumlaSdkApi.GetContractTemplatesRequest = {},
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.PaginatedResponse>> {
        const { skip, take } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (take != null) {
            _queryParams["take"] = take.toString();
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Production,
                "api/v1/contract-templates",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.PaginatedResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/contract-templates.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new contract template
     *
     * @param {OumlaSdkApi.CreateContractTemplateRequest} request
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contractTemplates.createContractTemplate({
     *         name: "name",
     *         description: "description",
     *         abi: [{
     *                 "key": "value"
     *             }],
     *         bytecode: "bytecode"
     *     })
     */
    public createContractTemplate(
        request: OumlaSdkApi.CreateContractTemplateRequest,
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createContractTemplate(request, requestOptions));
    }

    private async __createContractTemplate(
        request: OumlaSdkApi.CreateContractTemplateRequest,
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Production,
                "api/v1/contract-templates",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/contract-templates.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a specific contract template
     *
     * @param {string} templateId - Contract template ID
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contractTemplates.getContractTemplate("templateId")
     */
    public getContractTemplate(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getContractTemplate(templateId, requestOptions));
    }

    private async __getContractTemplate(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Production,
                `api/v1/contract-templates/${encodeURIComponent(templateId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/contract-templates/{templateId}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Delete a contract template
     *
     * @param {string} templateId - Contract template ID
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contractTemplates.deleteContractTemplate("templateId")
     */
    public deleteContractTemplate(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteContractTemplate(templateId, requestOptions));
    }

    private async __deleteContractTemplate(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Production,
                `api/v1/contract-templates/${encodeURIComponent(templateId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling DELETE /api/v1/contract-templates/{templateId}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve constructor information for a contract template
     *
     * @param {string} templateId - Contract template ID
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contractTemplates.getContractConstructor("templateId")
     */
    public getContractConstructor(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getContractConstructor(templateId, requestOptions));
    }

    private async __getContractConstructor(
        templateId: string,
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Production,
                `api/v1/contract-templates/${encodeURIComponent(templateId)}/constructorInfo`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/contract-templates/{templateId}/constructorInfo.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve function information for a contract template
     *
     * @param {string} templateId - Contract template ID
     * @param {OumlaSdkApi.GetTemplateFunctionsRequest} request
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contractTemplates.getTemplateFunctions("templateId", {
     *         functionSignature: "functionSignature"
     *     })
     */
    public getTemplateFunctions(
        templateId: string,
        request: OumlaSdkApi.GetTemplateFunctionsRequest = {},
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTemplateFunctions(templateId, request, requestOptions));
    }

    private async __getTemplateFunctions(
        templateId: string,
        request: OumlaSdkApi.GetTemplateFunctionsRequest = {},
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        const { functionSignature } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (functionSignature != null) {
            _queryParams["functionSignature"] = functionSignature;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Production,
                `api/v1/contract-templates/${encodeURIComponent(templateId)}/function`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/contract-templates/{templateId}/function.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Deploy a contract from a template
     *
     * @param {string} templateId - Contract template ID
     * @param {OumlaSdkApi.DeployContractRequest} request
     * @param {ContractTemplates.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.contractTemplates.deployContract("templateId", {
     *         network: "network",
     *         addressId: "addressId",
     *         clientShare: "clientShare"
     *     })
     */
    public deployContract(
        templateId: string,
        request: OumlaSdkApi.DeployContractRequest,
        requestOptions?: ContractTemplates.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.SuccessResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deployContract(templateId, request, requestOptions));
    }

    private async __deployContract(
        templateId: string,
        request: OumlaSdkApi.DeployContractRequest,
        requestOptions?: ContractTemplates.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.SuccessResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                "x-api-key": requestOptions?.apiKey ?? this._options?.apiKey,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Production,
                `api/v1/contract-templates/${encodeURIComponent(templateId)}/deploy`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as OumlaSdkApi.SuccessResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/contract-templates/{templateId}/deploy.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
