// This file was auto-generated by Fern from our API Definition.

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as OumlaSdkApi from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace DeployedContracts {
    export interface Options {
        environment?: core.Supplier<environments.OumlaSdkApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class DeployedContracts {
    protected readonly _options: DeployedContracts.Options;

    constructor(_options: DeployedContracts.Options) {
        this._options = _options;
    }

    /**
     * List deployed contracts with optional filters and pagination.
     *
     * @param {OumlaSdkApi.GetDeployedContractsRequest} request
     * @param {DeployedContracts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.deployedContracts.getDeployedContracts({
     *         skip: 0,
     *         take: 10,
     *         contractAddress: "contractAddress",
     *         networkId: "networkId",
     *         contractTemplateId: "contractTemplateId"
     *     })
     */
    public getDeployedContracts(
        request: OumlaSdkApi.GetDeployedContractsRequest = {},
        requestOptions?: DeployedContracts.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetDeployedContractsResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getDeployedContracts(request, requestOptions));
    }

    private async __getDeployedContracts(
        request: OumlaSdkApi.GetDeployedContractsRequest = {},
        requestOptions?: DeployedContracts.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetDeployedContractsResponseDto>> {
        const { skip, take, contractAddress, networkId, contractTemplateId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (skip != null) {
            _queryParams["skip"] = skip.toString();
        }

        if (take != null) {
            _queryParams["take"] = take.toString();
        }

        if (contractAddress != null) {
            _queryParams["contractAddress"] = contractAddress;
        }

        if (networkId != null) {
            _queryParams["networkId"] = networkId;
        }

        if (contractTemplateId != null) {
            _queryParams["contractTemplateId"] = contractTemplateId;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/deployed-contracts",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetDeployedContractsResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/deployed-contracts.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get a deployed contract by its deployment ID.
     *
     * @param {string} deploymentId - Deployment ID
     * @param {DeployedContracts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.deployedContracts.getDeployedContractById("deploymentId")
     */
    public getDeployedContractById(
        deploymentId: string,
        requestOptions?: DeployedContracts.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetDeployedContractByIdResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getDeployedContractById(deploymentId, requestOptions));
    }

    private async __getDeployedContractById(
        deploymentId: string,
        requestOptions?: DeployedContracts.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetDeployedContractByIdResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/deployed-contracts/${encodeURIComponent(deploymentId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetDeployedContractByIdResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/deployed-contracts/{deploymentId}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get a deployed contract by contract address and networkId.
     *
     * @param {string} contractAddress - Contract address
     * @param {string} networkId - Network Id
     * @param {DeployedContracts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.deployedContracts.getDeployedContractByAddress("contractAddress", "networkId")
     */
    public getDeployedContractByAddress(
        contractAddress: string,
        networkId: string,
        requestOptions?: DeployedContracts.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetDeployedContractByAddressResponseDto> {
        return core.HttpResponsePromise.fromPromise(
            this.__getDeployedContractByAddress(contractAddress, networkId, requestOptions),
        );
    }

    private async __getDeployedContractByAddress(
        contractAddress: string,
        networkId: string,
        requestOptions?: DeployedContracts.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetDeployedContractByAddressResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                `api/v1/deployed-contracts/${encodeURIComponent(contractAddress)}/${encodeURIComponent(networkId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetDeployedContractByAddressResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/deployed-contracts/{contractAddress}/{networkId}.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Fetch contract ABI from chain/relayer by address and network.
     *
     * @param {OumlaSdkApi.FetchContractAbiRequestBodyDto} request
     * @param {DeployedContracts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.NotFoundError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.deployedContracts.fetchContractAbi({
     *         contractAddress: "contractAddress",
     *         networkId: "networkId"
     *     })
     */
    public fetchContractAbi(
        request: OumlaSdkApi.FetchContractAbiRequestBodyDto,
        requestOptions?: DeployedContracts.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.FetchContractAbiResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__fetchContractAbi(request, requestOptions));
    }

    private async __fetchContractAbi(
        request: OumlaSdkApi.FetchContractAbiRequestBodyDto,
        requestOptions?: DeployedContracts.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.FetchContractAbiResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/deployed-contracts/fetch-abi",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.FetchContractAbiResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new OumlaSdkApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/deployed-contracts/fetch-abi.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Add or update ABI for a deployed contract.
     *
     * @param {OumlaSdkApi.AddContractAbiRequestBodyDto} request
     * @param {DeployedContracts.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link OumlaSdkApi.BadRequestError}
     * @throws {@link OumlaSdkApi.UnauthorizedError}
     * @throws {@link OumlaSdkApi.ForbiddenError}
     * @throws {@link OumlaSdkApi.ConflictError}
     * @throws {@link OumlaSdkApi.InternalServerError}
     *
     * @example
     *     await client.deployedContracts.addContractAbi({
     *         contractAddress: "contractAddress",
     *         networkId: "networkId",
     *         name: "name",
     *         abi: [[]]
     *     })
     */
    public addContractAbi(
        request: OumlaSdkApi.AddContractAbiRequestBodyDto,
        requestOptions?: DeployedContracts.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.AddContractAbiResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__addContractAbi(request, requestOptions));
    }

    private async __addContractAbi(
        request: OumlaSdkApi.AddContractAbiRequestBodyDto,
        requestOptions?: DeployedContracts.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.AddContractAbiResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/deployed-contracts/add-abi",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.AddContractAbiResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new OumlaSdkApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new OumlaSdkApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new OumlaSdkApi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new OumlaSdkApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new OumlaSdkApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.OumlaSdkApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling POST /api/v1/deployed-contracts/add-abi.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
