// This file was auto-generated by Fern from our API Definition.

export const GetCollectionTokensRequestType = {
    Mint: "MINT",
    Burn: "BURN",
} as const;
export type GetCollectionTokensRequestType =
    (typeof GetCollectionTokensRequestType)[keyof typeof GetCollectionTokensRequestType];
