// This file was auto-generated by Fern from our API Definition.

export interface MintTokenResponse {
    mint?: MintTokenResponse.Mint;
}

export namespace MintTokenResponse {
    export interface Mint {
        workflowId?: string;
        status?: string;
    }
}
