// This file was auto-generated by Fern from our API Definition.

export interface UnlinkTokenResponse {
    result?: UnlinkTokenResponse.Result;
}

export namespace UnlinkTokenResponse {
    export interface Result {
        success?: boolean;
    }
}
