// This file was auto-generated by Fern from our API Definition.

export const GetDeployedContractAbiRequestNetwork = {
    TBtc: "tBTC",
    TEth: "tETH",
    Avax: "AVAX",
    Fuji: "FUJI",
    Sandbox: "SANDBOX",
} as const;
export type GetDeployedContractAbiRequestNetwork =
    (typeof GetDeployedContractAbiRequestNetwork)[keyof typeof GetDeployedContractAbiRequestNetwork];
