// This file was auto-generated by Fern from our API Definition.

export const GetTransactionReceiptRequestNetwork = {
    TBtc: "tBTC",
    TEth: "tETH",
    Avax: "AVAX",
    Fuji: "FUJI",
    Sandbox: "SANDBOX",
} as const;
export type GetTransactionReceiptRequestNetwork =
    (typeof GetTransactionReceiptRequestNetwork)[keyof typeof GetTransactionReceiptRequestNetwork];
