// This file was auto-generated by Fern from our API Definition.

export interface WriteCallFunctionResponse {
    result?: WriteCallFunctionResponse.Result;
}

export namespace WriteCallFunctionResponse {
    export interface Result {
        workflowId?: string;
        status?: string;
    }
}
