// This file was auto-generated by Fern from our API Definition.

export const WriteCallFunctionRequestNetwork = {
    TBtc: "tBTC",
    TEth: "tETH",
    Avax: "AVAX",
    Fuji: "FUJI",
    Sandbox: "SANDBOX",
} as const;
export type WriteCallFunctionRequestNetwork =
    (typeof WriteCallFunctionRequestNetwork)[keyof typeof WriteCallFunctionRequestNetwork];
