// This file was auto-generated by Fern from our API Definition.

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as OumlaSdkApi from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Networks {
    export interface Options {
        environment?: core.Supplier<environments.OumlaSdkApiEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-sdk-version header */
        sdkVersion?: "1.0.0";
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class Networks {
    protected readonly _options: Networks.Options;

    constructor(_options: Networks.Options) {
        this._options = _options;
    }

    /**
     * Returns the enabled-networks catalog (ID, name, alias) from cache. Accessible to any authenticated user — exposes only non-sensitive metadata. On cache miss, rebuilds the index from the database.
     *
     * @param {Networks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.networks.getEnabledNetworks()
     */
    public getEnabledNetworks(
        requestOptions?: Networks.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetEnabledNetworksResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getEnabledNetworks(requestOptions));
    }

    private async __getEnabledNetworks(
        requestOptions?: Networks.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetEnabledNetworksResponseDto>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/network/enabled",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetEnabledNetworksResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError("Timeout exceeded when calling GET /api/v1/network/enabled.");
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get networks available for your organization.
     *
     * @param {OumlaSdkApi.GetNetworksRequest} request
     * @param {Networks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.networks.getNetworks({
     *         skip: 0,
     *         take: 10,
     *         enabled: true,
     *         name: "name"
     *     })
     */
    public getNetworks(
        request: OumlaSdkApi.GetNetworksRequest,
        requestOptions?: Networks.RequestOptions,
    ): core.HttpResponsePromise<OumlaSdkApi.GetOrgNetworksResponseDto> {
        return core.HttpResponsePromise.fromPromise(this.__getNetworks(request, requestOptions));
    }

    private async __getNetworks(
        request: OumlaSdkApi.GetNetworksRequest,
        requestOptions?: Networks.RequestOptions,
    ): Promise<core.WithRawResponse<OumlaSdkApi.GetOrgNetworksResponseDto>> {
        const { skip, take, enabled, name } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["skip"] = skip.toString();
        _queryParams["take"] = take.toString();
        if (enabled != null) {
            _queryParams["enabled"] = enabled.toString();
        }

        if (name != null) {
            _queryParams["name"] = name;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                "x-sdk-version": requestOptions?.sdkVersion ?? "1.0.0",
                ...(await this._getCustomAuthorizationHeaders()),
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.OumlaSdkApiEnvironment.Mainnet,
                "api/v1/network/organization",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as OumlaSdkApi.GetOrgNetworksResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.OumlaSdkApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.OumlaSdkApiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.OumlaSdkApiTimeoutError(
                    "Timeout exceeded when calling GET /api/v1/network/organization.",
                );
            case "unknown":
                throw new errors.OumlaSdkApiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "x-api-key": apiKeyValue };
    }
}
