// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         skip: 0,
 *         take: 10,
 *         enabled: true,
 *         name: "name"
 *     }
 */
export interface GetNetworksRequest {
    skip: number;
    take: number;
    /** Filter by enabled status (true = only enabled networks) */
    enabled?: boolean;
    /** Filter by network name */
    name?: string;
}
